symbols:
  - code: L2605
    start: 2025-12-01
  - code: LC2605
    start: 2025-11-05

freq: "60m"
analysis:
  window_strength: 5
  window_zone: 60
  bins_pct: 0.5
  beta: 0.7
  half_life: 1000000000
  quantile: 0.8
out_dir: "./data"
timezone: "Asia/Shanghai"
