symbols:
  - code: JM2601
    start: 2025-10-30
  - code: JM2605
    start: 2025-10-30

freq: "60m"
analysis:
  window_strength: 5
  window_zone: 60
  bins_pct: 0.5
  beta: 0.7
  half_life: 1000000000
  quantile: 0.8
out_dir: "./data"
timezone: "Asia/Shanghai"
